CREATE TABLE if not EXISTS tbl_student
(
    id              int8 GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    student_name    varchar(50)                           NOT NULL,
    student_surname varchar(50)                           NOT NULL,
    student_age     int4                                  NOT NULL,
    CONSTRAINT student_age_check CHECK ((student_age >= 1)),
    CONSTRAINT student_pkey PRIMARY KEY (id)
);